### ISSUE TITLE
 ModuleNotFoundError: No module named 'comfy_extras.nodes_sd3' 

### ISSUE THREAD

**Issue by BAK-HOME** [liusida/ComfyUI-SD3-nodes#3]
I run comfyui in ubuntu22.04. After installing the node ComfyUI-SD3-nodes, I get this error. No module named 'comfy_extras.nodes_sd3', and the corresponding error is: Traceback (most recent call last): 
  File "/home/comfyui/nodes.py", line 1887, in load_custom_node 
    module_spec.loader.exec_module(module) 
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module 
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed 
  File "/home/comfyui/custom_nodes/ComfyUI-SD3-nodes/__init__.py", line 2, in <module> 
    from .nodes.sd3_load_clips import * 
  File "/home/comfyui/custom_nodes/ComfyUI-SD3-nodes/nodes/sd3_load_clips.py", line 2, in <module> 
    from comfy_extras.nodes_sd3 import TripleCLIPLoader。 
 How can we solve this problem?

**Comment by liusida** [comment]
Please update the ComfyUI to the latest version, and it'll resolve this issue.

**Comment by liusida** [comment]
You can click "Update All" or "Update ComfyUI" in the middle of this dialog from ComfyUI-Manager:
![image](https://github.com/liusida/ComfyUI-SD3-nodes/assets/14249458/b51831c9-fdf6-4f5d-b7f0-f7cbcab01b68)

Or manually `git pull` in the ComfyUI directory.
